using Broiler.JavaScript.Core;
using Broiler.JavaScript.Core.Core;
using Broiler.JavaScript.Core.Core.Module;
using Broiler.JavaScript.Ast;
using Broiler.JavaScript.Parser;

namespace Broiler.JavaScript.Integration.Tests;

public class IntegrationTests
{
    [Fact]
    public void FullPipeline_ParseCompileExecute()
    {
        // Parse
        var code = "2 + 3";
        var stream = new FastTokenStream(new StringSpan(code));
        var parser = new FastParser(stream);
        var program = parser.ParseProgram();
        Assert.NotNull(program);

        // Compile and Execute via JSContext
        using var ctx = new JSContext();
        var result = ctx.Eval(code);
        Assert.Equal(5.0, result.DoubleValue);
    }

    [Fact]
    public void CompilerRegistration_Works()
    {
        // Creating a JSContext triggers ModuleInitializer chain
        // which registers FastCompiler, BuiltIns, and CLR interop
        using var ctx = new JSContext();
        var result = ctx.Eval("typeof undefined");
        Assert.Equal("undefined", result.ToString());
    }

    [Fact]
    public void BuiltInsRegistration_Works()
    {
        // Ensure the BuiltIns assembly is loaded so its ModuleInitializer fires
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Core.Core.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // WeakRef should be available after BuiltIns registration
        var result = ctx.Eval("typeof WeakRef");
        Assert.Equal("function", result.ToString());
    }

    [Fact]
    public void ClrRegistration_Works()
    {
        using var ctx = new JSContext();
        // CLR interop should be functional after registration
        Assert.NotNull(JSContext.Current);
    }

    [Fact]
    public void TypeForwarding_ResolvesCorrectly()
    {
        // Types forwarded from Core should resolve properly
        var jsValueType = typeof(JSValue);
        Assert.NotNull(jsValueType);
        Assert.Equal("Broiler.JavaScript.Core.Core", jsValueType.Namespace);
    }

    [Fact]
    public void JSModuleContext_WithCompiler_Works()
    {
        var moduleCtx = new JSModuleContext();
        Assert.NotNull(moduleCtx);
        // Module context should work with the registered compiler
        var exports = new JSObject();
        moduleCtx.RegisterModule(
            KeyStrings.GetOrCreate(new StringSpan("test")),
            exports);
    }

    [Fact]
    public void SourceGenerator_IndependentPerAssembly()
    {
        // Both Core and BuiltIns assemblies should have independent Names classes
        // generated by JSClassGenerator. Verify both assemblies load correctly.
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(
            typeof(Broiler.JavaScript.Core.Core.Weak.JSWeakRef).TypeHandle);
        using var ctx = new JSContext();
        // This exercises code paths in both Core and BuiltIns assemblies
        var result = ctx.Eval("typeof WeakRef");
        Assert.Equal("function", result.ToString());
    }
}
