using System.Reflection;
using System.Text;

namespace Broiler.Cli.Tests;

/// <summary>
/// Shared helpers for HtmlBridge architecture and public-API-surface guards.
/// See <c>docs/architecture/htmlbridge.md#dependency-and-ownership-rules</c>.
/// </summary>
internal static class RepoPaths
{
    /// <summary>Walk up from the test output directory to the repository root (the folder
    /// containing <c>Broiler.slnx</c>).</summary>
    public static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Broiler.slnx")))
                return directory.FullName;

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate Broiler.slnx from the test output directory.");
    }
}

/// <summary>
/// Produces a deterministic, human-readable rendering of an assembly's public
/// (exported) API surface, used to freeze the v2 bridge contract against silent
/// drift during the decomposition. The format is intentionally stable and sorted so
/// a diff pinpoints exactly which member was added, removed or re-signed.
/// </summary>
internal static class PublicApiSurface
{
    public static string Describe(Assembly assembly)
    {
        var sb = new StringBuilder();
        sb.Append("// Public API surface of ").Append(assembly.GetName().Name).Append('\n');
        sb.Append("// Generated by HtmlBridgePublicApiSnapshotTests (P0.2). Do not edit by hand;\n");
        sb.Append("// regenerate with UPDATE_API_BASELINES=1 when the change is intentional.\n");

        foreach (var type in assembly.GetExportedTypes().OrderBy(static t => t.FullName, StringComparer.Ordinal))
        {
            sb.Append("TYPE ").Append(TypeName(type));

            var bases = new List<string>();
            if (type.BaseType is { } baseType &&
                baseType != typeof(object) && baseType != typeof(ValueType) && baseType != typeof(Enum))
            {
                bases.Add(TypeName(baseType));
            }

            bases.AddRange(type.GetInterfaces()
                .Where(static i => i.IsPublic || i.IsNestedPublic)
                .Select(TypeName)
                .OrderBy(static n => n, StringComparer.Ordinal));

            if (bases.Count > 0)
                sb.Append(" : ").Append(string.Join(", ", bases));

            sb.Append('\n');

            foreach (var member in DescribeMembers(type))
                sb.Append("  ").Append(member).Append('\n');
        }

        return sb.ToString();
    }

    private static IEnumerable<string> DescribeMembers(Type type)
    {
        const BindingFlags flags =
            BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        var members = new List<string>();

        foreach (var ctor in type.GetConstructors(flags))
            members.Add($"ctor {Signature(ctor.GetParameters())}");

        // IsSpecialName drops property/event accessors (rendered separately below) and
        // operators; the bridge public surface contains no operator overloads.
        foreach (var method in type.GetMethods(flags).Where(static m => !m.IsSpecialName))
        {
            var generic = method.IsGenericMethodDefinition
                ? "<" + string.Join(", ", method.GetGenericArguments().Select(static a => a.Name)) + ">"
                : string.Empty;
            members.Add($"method {TypeName(method.ReturnType)} {method.Name}{generic}{Signature(method.GetParameters())}");
        }

        foreach (var property in type.GetProperties(flags))
        {
            var accessors = new List<string>();
            if (property.GetMethod is { IsPublic: true }) accessors.Add("get");
            if (property.SetMethod is { IsPublic: true }) accessors.Add("set");
            var indexers = property.GetIndexParameters();
            var index = indexers.Length > 0 ? Signature(indexers) : string.Empty;
            members.Add($"property {TypeName(property.PropertyType)} {property.Name}{index} {{ {string.Join(" ", accessors.Select(static a => a + ";"))} }}");
        }

        foreach (var field in type.GetFields(flags))
        {
            var modifier = field.IsLiteral
                ? "const "
                : (field.IsInitOnly ? "readonly " : string.Empty) + (field.IsStatic ? "static " : string.Empty);
            members.Add($"field {modifier}{TypeName(field.FieldType)} {field.Name}");
        }

        foreach (var evt in type.GetEvents(flags))
            members.Add($"event {TypeName(evt.EventHandlerType!)} {evt.Name}");

        members.Sort(StringComparer.Ordinal);
        return members;
    }

    private static string Signature(ParameterInfo[] parameters) =>
        "(" + string.Join(", ", parameters.Select(static p => TypeName(p.ParameterType))) + ")";

    private static string TypeName(Type type)
    {
        if (type.IsGenericParameter)
            return type.Name;
        if (type.IsArray)
            return TypeName(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
        if (type.IsByRef)
            return "ref " + TypeName(type.GetElementType()!);
        if (type.IsPointer)
            return TypeName(type.GetElementType()!) + "*";

        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            var name = definition.FullName ?? definition.Name;
            var tick = name.IndexOf('`');
            if (tick >= 0)
                name = name[..tick];
            var arguments = type.GetGenericArguments().Select(TypeName);
            return name + "<" + string.Join(", ", arguments) + ">";
        }

        return type.FullName ?? type.Name;
    }
}
