using Broiler.HtmlBridge;
using Broiler.HtmlBridge.Dom;
using Broiler.JavaScript.Engine;

namespace Broiler.Cli.Tests;

/// <summary>
/// Guards grid-track-based intrinsic (shrink-to-fit) width (roadmap #1248
/// Workstream A / E tail). A grid with a fixed column template sizes its
/// <c>min-content</c>/<c>max-content</c>/<c>fit-content</c>/<c>float</c> width to
/// the sum of its column tracks (+ gaps + own padding/border), rather than the
/// max-content of its (often empty) inline content — which collapsed the container
/// (WPT css-grid grid-gutters-and-tracks-001's <c>.fit-content</c> grids, the
/// <c>…-margin-border-padding-vertical-rl</c> container, …).
///
/// Cases here are viewport-independent (they either don't use the containing
/// block's available space, or have min-content == max-content). The
/// <c>fit-content</c> case where min-content ≠ max-content (e.g. a <c>minmax()</c>
/// track) depends on the available space, so it is only exact on a real viewport
/// (CI), not this harness. Vertical writing modes are out of scope (the physical
/// width axis must map through the rotation) and keep their existing sizing.
/// </summary>
public sealed class GridIntrinsicWidthTests
{
    private static double ContainerWidth(string style, string items = "")
    {
        string html =
            "<!DOCTYPE html><html><head></head><body style=\"margin:0\">"
            + $"<div id=\"g\" style=\"{style}\" data-offset-x=\"0\" data-offset-y=\"0\" data-expected-width=\"0\" data-expected-height=\"0\">{items}</div>"
            + "</body></html>";
        using var context = new JSContext();
        var bridge = new DomBridge();
        bridge.Attach(context, html, "file:///giw.html");
        var m = bridge.EvaluateCheckLayoutAssertions()
            .Where(a => a.Element.Contains("#g")).ToDictionary(a => a.Property, a => a.Actual);
        return m.TryGetValue("width", out var w) ? w : double.NaN;
    }

    /// <summary>An empty grid item placed with the given <c>grid-column</c>.</summary>
    private static string Item(string gridColumn = "") =>
        $"<div style=\"{(gridColumn.Length == 0 ? "" : "grid-column:" + gridColumn)}\"></div>";

    private const string Base = "display:grid;position:relative;grid-template-rows:10px;";

    [Fact]
    public void MaxContentGrid_SumsColumnTracks()
    {
        Assert.Equal(200, ContainerWidth(Base + "width:max-content;grid-template-columns:100px 100px;"), 1);
        Assert.Equal(160, ContainerWidth(Base + "width:max-content;grid-template-columns:30px 50px 80px;"), 1);
        // minmax(): max-content uses the max side.
        Assert.Equal(50, ContainerWidth(Base + "width:max-content;grid-template-columns:minmax(10px,50px);"), 1);
    }

    [Fact]
    public void MinContentGrid_UsesMinTrackSides()
    {
        // minmax(): min-content uses the min side.
        Assert.Equal(10, ContainerWidth(Base + "width:min-content;grid-template-columns:minmax(10px,50px);"), 1);
        Assert.Equal(200, ContainerWidth(Base + "width:min-content;grid-template-columns:100px 100px;"), 1);
    }

    [Fact]
    public void FixedTrackShrinkToFit_SizesToTracksPlusGapsAndBorder()
    {
        // fit-content and float with fixed tracks (min-content == max-content).
        Assert.Equal(200, ContainerWidth(Base + "width:fit-content;grid-template-columns:100px 100px;"), 1);
        Assert.Equal(100, ContainerWidth(Base + "float:left;grid-template-columns:60px 40px;"), 1);
        // column-gap adds to the container.
        Assert.Equal(220, ContainerWidth(Base + "width:fit-content;grid-template-columns:100px 100px;column-gap:20px;"), 1);
        // padding + border count once (frame-correct).
        Assert.Equal(220, ContainerWidth(Base + "width:fit-content;grid-template-columns:100px 100px;padding:0 5px;border:5px solid;"), 1);
    }

    [Fact]
    public void NonFixedTracks_DeclineAndKeepPriorBehaviour()
    {
        // auto-fill / fr / auto need the real track pass, so the intrinsic-width
        // shortcut declines and the grid keeps the existing shrink-to-fit path
        // (which, for these empty grids, does NOT sum the tracks). A mixed
        // fixed+auto template must therefore NOT resolve to just its fixed track.
        double autoFill = ContainerWidth(Base + "float:left;grid-template-columns:repeat(auto-fill,100px);");
        Assert.True(autoFill < 150, $"auto-fill grid must decline the fixed-track shortcut (got {autoFill})");
        double mixed = ContainerWidth(Base + "width:max-content;grid-template-columns:100px auto;");
        Assert.True(Math.Abs(mixed - 100) > 0.5, $"fixed+auto template must decline the shortcut (got {mixed})");
    }

    // ── Implicit columns ──────────────────────────────────────────────────────
    //
    // The intrinsic width is the sum of the tracks the layout will actually
    // have, not just the ones grid-template-columns lists. A column generated by
    // auto-placement, or by a grid-column reaching past the template, is sized
    // from grid-auto-columns exactly as the definite-width pass sizes it — so a
    // shrink-to-fit grid whose columns are all implicit stops collapsing to the
    // (zero) intrinsic width of its empty items.

    private const string ImplicitBase = Base + "grid-auto-columns:15px;grid-auto-rows:10px;";

    [Fact]
    public void ImplicitColumns_SizeFromGridAutoColumns()
    {
        // No template at all: the one auto-placed item generates a single 15px
        // implicit column. Before, the method bailed on the empty template and
        // the caller measured inline content — zero, for an empty div.
        Assert.Equal(15, ContainerWidth(ImplicitBase + "width:max-content;", Item()), 1);

        // A grid-column reaching past the (absent) template generates the tracks
        // it skips as well as the ones it spans: 6 columns × 15px.
        Assert.Equal(90, ContainerWidth(ImplicitBase + "width:max-content;", Item("3 / span 4")), 1);

        // An item spilling out of a fixed template mixes the two: the template's
        // own tracks, then grid-auto-columns for what it ran past.
        Assert.Equal(70, ContainerWidth(
            ImplicitBase + "width:max-content;grid-template-columns:20px 20px;", Item("3 / span 2")), 1);
    }

    [Fact]
    public void ImplicitColumns_ChargeGapsAcrossTheFullColumnCount()
    {
        // Three implicit columns carry two gaps, not the zero a template-only
        // count (specs.Count - 1, with no specs) would have charged.
        Assert.Equal(53, ContainerWidth(
            ImplicitBase + "width:max-content;column-gap:4px;", Item("1 / span 3")), 1);
    }

    [Fact]
    public void ImplicitColumns_ShrinkToFitFloatSizesToItsTracks()
    {
        // The float path (ComputeShrinkToFitWidth) shares the method, so a float
        // whose columns are all implicit sizes to them rather than to its
        // containing block.
        Assert.Equal(30, ContainerWidth(ImplicitBase + "float:left;", Item("span 2")), 1);
    }

    [Fact]
    public void ImplicitColumnWithAutoSizing_DeclinesAndKeepsPriorBehaviour()
    {
        // grid-auto-columns defaults to 'auto', which needs the real track pass
        // (the tracks come from their items' contributions). That is what bounds
        // this change: the method must decline rather than invent a width, so
        // every grid that does not declare a fixed grid-auto-columns keeps the
        // content-based fallback it had before.
        double noAutoCols = ContainerWidth(Base + "width:max-content;", Item());
        Assert.True(noAutoCols < 1,
            $"an implicit auto column must decline the fixed-track shortcut (got {noAutoCols})");

        // Same when only *some* of the columns are implicit: a fixed template
        // does not license guessing at the tracks past it.
        double spilled = ContainerWidth(Base + "width:max-content;grid-template-columns:20px 20px;",
            Item("3 / span 2"));
        Assert.True(Math.Abs(spilled - 40) > 0.5,
            $"a spilled item must not resolve to just the template's tracks (got {spilled})");
    }

    [Fact]
    public void NoImplicitColumns_KeepsTemplateOnlySizing()
    {
        // The regression guard for the placement pass this now runs: an item that
        // fits inside the template generates nothing, so the width is the
        // template's, and grid-auto-columns is never consulted.
        Assert.Equal(50, ContainerWidth(
            ImplicitBase + "width:max-content;grid-template-columns:20px 30px;", Item()), 1);
        Assert.Equal(50, ContainerWidth(
            Base + "width:max-content;grid-template-columns:20px 30px;", Item() + Item()), 1);

        // Row flow wraps within the template instead of widening it, so three
        // items in a two-column grid are still two columns wide.
        Assert.Equal(50, ContainerWidth(
            ImplicitBase + "width:max-content;grid-template-columns:20px 30px;",
            Item() + Item() + Item()), 1);
    }

    [Fact]
    public void ColumnFlow_GeneratesAColumnPerRowfulOfItems()
    {
        // grid-auto-flow: column fills the explicit rows first and then starts a
        // new (implicit) column, so the column count depends on the row template
        // — which is why the count is taken from the same placement the real
        // pass runs rather than from the column template alone.
        const string flow = ImplicitBase + "width:max-content;grid-auto-flow:column;grid-template-rows:10px 10px;";

        Assert.Equal(15, ContainerWidth(flow, Item() + Item()), 1);
        Assert.Equal(30, ContainerWidth(flow, Item() + Item() + Item()), 1);
    }
}
