#requires -Version 5.1
<#
.SYNOPSIS
    (Re)generate the convenience meta-packages Broiler.<Component>.All for the
    large component families (Media, Input, UI).

.DESCRIPTION
    A meta-package carries no assembly (IncludeBuildOutput=false); it only
    declares PackageReferences to every cross-platform, shippable library in
    its component, so a consumer can install one id to get the whole family.

    Membership is derived by scanning the component for .csproj files and
    excluding, by naming convention:
      *.Tests / *.Demo / *.Diagnostic   -> not shippable
      *.Windows / *.Linux / *.MediaFoundation -> platform-native (opt-in
                                                  separately, keeps the meta
                                                  cross-platform)
      *.All                              -> the meta itself
    Re-run after adding or removing a library in one of these components.
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# component -> meta description + tags
$metas = @{
    'Broiler.Media' = @{
        Desc = 'Meta-package that pulls in the full cross-platform Broiler.Media stack (core, audio, image, and video plus their managed implementations). Platform-native backends (e.g. MediaFoundation) are separate packages.'
        Tags = 'broiler;media;audio;image;video;meta'
    }
    'Broiler.Input' = @{
        Desc = 'Meta-package that pulls in the cross-platform Broiler.Input device contracts (keyboard, mouse, pen, touch, text, camera, microphone). Platform backends (*.Windows, *.Linux) are separate packages.'
        Tags = 'broiler;input;devices;meta'
    }
    'Broiler.UI' = @{
        Desc = 'Meta-package that pulls in the complete Broiler retained-mode UI toolkit: every control contract and its Standard implementation.'
        Tags = 'broiler;ui;controls;widgets;meta'
    }
}

$excludeSuffix = '\.(Tests|Demo|Diagnostic|Windows|Linux|MediaFoundation|All)$'

foreach ($component in $metas.Keys | Sort-Object) {
    $componentDir = Join-Path $repoRoot $component
    $metaId   = "$component.All"
    $metaDir  = Join-Path $componentDir $metaId
    $metaProj = Join-Path $metaDir "$metaId.csproj"

    # Discover member projects.
    $members = Get-ChildItem -Path $componentDir -Recurse -Filter '*.csproj' |
        Where-Object { $_.FullName -notmatch '[\\/](obj|bin)[\\/]' } |
        Where-Object { [IO.Path]::GetFileNameWithoutExtension($_.Name) -notmatch $excludeSuffix } |
        Sort-Object FullName

    if (-not $members) { Write-Warning "no members found for $metaId"; continue }

    # metaDir is one level below componentDir, so a member's path relative to
    # metaDir is '..\' + its path relative to componentDir. (PS 5.1 has no
    # Path.GetRelativePath.)
    $componentPrefix = $componentDir.TrimEnd('\') + '\'
    $refs = foreach ($m in $members) {
        $underComponent = $m.FullName.Substring($componentPrefix.Length)
        $rel = '..\' + ($underComponent -replace '/', '\')
        "    <ProjectReference Include=`"$rel`" />"
    }

    $csproj = @"
<Project Sdk="Microsoft.NET.Sdk">

  <!-- GENERATED by scripts/gen-metapackages.ps1 - do not edit by hand. -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>$metaId</PackageId>
    <Description>$($metas[$component].Desc)</Description>
    <PackageTags>$($metas[$component].Tags)</PackageTags>

    <!-- Meta-package: ship dependencies only, no assembly. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- NU5128: a dependency group with no matching lib folder is expected
         for a dependencies-only meta-package. -->
    <NoWarn>`$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
$($refs -join "`r`n")
  </ItemGroup>

</Project>
"@

    if (-not (Test-Path $metaDir)) {
        if ($PSCmdlet.ShouldProcess($metaDir, 'create meta dir')) {
            New-Item -ItemType Directory -Path $metaDir | Out-Null
        }
    }
    if ($PSCmdlet.ShouldProcess($metaProj, "write $metaId.csproj ($($members.Count) members)")) {
        Set-Content -Path $metaProj -Value $csproj -Encoding UTF8
    }
    Write-Host "$metaId <- $($members.Count) member projects"
}
